### ISSUE TITLE
Peut-être une erreur de programmation

### ISSUE THREAD

**Issue by benjamin-feron** [karutaproject/karuta-backend_legacy#81]
Bonjour,

Dans le fichier /src/com/portfolio/rest/RestServicePortfolio.java à la ligne 4300, on peut lire :

`if (ldapvalues[1] != null | ldapvalues[2] != null | ldapvalues[3] != null)`

Ne faudrait il pas plutôt doubler les "|" comme ceci ? :

`if (ldapvalues[1] != null || ldapvalues[2] != null || ldapvalues[3] != null)`

Avec de simples "|", il s'agit d'un OU binaire.

Voici le [commit](https://github.com/karutaproject/karuta-backend_legacy/commit/598d48acfcb86874f97838a107d84fff020beb50) correspondant.

Benjamin Féron

**Comment by nobry** [comment]
Dans la finalité le code s'execute correctement, mais j'avoue que c'est plus propre avec le OU logique.
J'ai fais les changements dans le commit https://github.com/karutaproject/karuta-backend_legacy/commit/c08bd69a96608918a406ca39fc97954b6ff59ad2

Merci du commentaire.

**Comment by benjamin-feron** [comment]
Avec plaisir
