### ISSUE TITLE
Use of Mysql 8 and upper

### ISSUE THREAD

**Issue by jgribonvald** [karutaproject/karuta-backend_legacy#94]
Since Mysql 8 the function PASSWORD() was deleted. MariaDB doesn't have this problem.

So this line doesn't work: https://github.com/karutaproject/karuta-backend_legacy/blob/master/src/com/eportfolium/karuta/data/provider/MysqlDataProvider.java#L14396

**Comment by nobry** [comment]
Should be fixed with bf819da45f87e847d3a12104ef505e7910209661
If needed, a salt could be added.
