### ISSUE TITLE
Possible issue ?

### ISSUE THREAD

**Issue by jgribonvald** [karutaproject/karuta-backend_legacy#96]
Is there a break on case: missing here: https://github.com/karutaproject/karuta-backend_legacy/blob/master/src/com/eportfolium/karuta/data/attachment/DirectURLService.java#L220

and also on https://github.com/karutaproject/karuta-backend_legacy/blob/master/src/com/eportfolium/karuta/data/attachment/DirectURLService.java#L233

Thanks

**Comment by nobry** [comment]
This part is fine it's different stage of the process that can be initiated depending on the need:
- Create an account
- Share a specific portfolio
- Log via approved email
If accounts are already imported, just create defined portfolio
If everything is already created, log with email.
